### ISSUE TITLE
Unable to create VM due to network config issue

### ISSUE THREAD

**Issue by trigun539** [terra-farm/terraform-provider-xenorchestra#30]
My tf file contains the following network config:

```
data "xenorchestra_pif" "pif" {
  device = "eth0"
  vlan = -1
}
```

This is the Xen Orchestra output:

```
vm.create
{
  "CPUs": 2,
  "VIFs": [
    {
      "network": "0441bdfb-f87c-e189-6b5f-4d7e88fcaa4a"
    }
  ],
  "bootAfterCreate": true,
.....

```

Error:

```
"message": "no object with UUID or opaque ref: 0441bdfb-f87c-e189-6b5f-4d7e88fcaa4a",
```

Also tried using "eth4" for device, but getting same error.

How can I avoid this issue? Trying to follow documentation but not sure why this is not working. 

Xen Orchestra is setup with two XCP NG hosts. Each host has 8 NICs eth0-eth7.

**Comment by olivierlambert** [comment]
Are you sure about the network UUID?

**Comment by trigun539** [comment]
@olivierlambert So, in the example for creating a VM. I can only set device / clan. The network UUID is automatically created somehow by the provider or Xen Orchestra. 

Not sure how to give it a valid network UUID.

**Comment by olivierlambert** [comment]
Check on your host about the Network ID, maybe it's something wrong fetch from `${data.xenorchestra_pif.pif.network}`

**Comment by trigun539** [comment]
@olivierlambert Since my XO has connection to two xcpng hosts. Checked hosts for network UUIDs and seems like Terraform randomly selects a host to create the VM in. 

The problem is trying to match the storage to the randomly selected xcpnghost. 

After a couple tests of changing the SR to match the right network for the right host. Now, there is a different issue:

Error:

```
vm.create
{
  "CPUs": 2,
  "VIFs": [
    {
      "network": "8b2a3e6d-a401-3f07-3436-1434e192df25"
    }
  ],
  "bootAfterCreate": true,
  "cloudConfig": "#cloud-init\ntiemzone: America/New_York\nhostname: terraformtest\npackage_update: true\npackage_upgrade: true\nusers:\n  - name: test\n    gecos: Test User\n    groups: sudo\n    passwd: test\n    sudo: ['ALL=(ALL) NOPASSWD:ALL']\n\nnetwork:\n  version: 2\n  ethernets:\n    eno1:\n      dhcp4: no\n      addresses: [192.168.0.42/24]\n      gateway4: 192.168.0.1\n      nameservers:\n         addresses: [192.168.0.1]\n\nruncmd:\n - [ ls, -l, / ]\n - [ sh, -xc, \"echo $(date) ': hello world!'\" ]\n - [ sh, -c, echo \"=========hello world'=========\" ]\n - ls -l /root\n",
  "coreOs": false,
  "cpuCap": null,
  "cpuWeight": null,
  "existingDisks": {
    "0": {
      "$SR": "388ccc18-9b21-22cc-dfa9-db4c8c3a4959",
      "name_label": "Terraform_disk_imavo",
      "size": 32212254720
    }
  },
  "memoryMax": 1073733632,
  "name_description": "Created by Terraform Script",
  "name_label": "TerraformVMEdited",
  "template": "74ae424d-a1d3-4d96-9827-d1d60a4c7511"
}
{
  "message": "no object with UUID or opaque ref: undefined",
  "name": "Error",
  "stack": "Error: no object with UUID or opaque ref: undefined
    at Xapi.getObject (/etc/xo/xo-builds/xen-orchestra-201927041953/packages/xen-api/src/index.js:560:10)
    at Xapi.getObject.args [as getObject] (/etc/xo/xo-builds/xen-orchestra-201927041953/packages/xo-server/src/xapi/index.js:109:23)
    at /etc/xo/xo-builds/xen-orchestra-201927041953/packages/xo-server/src/xapi/index.js:2386:20
    at Generator.next (<anonymous>)
    at asyncGeneratorStep (/etc/xo/xo-builds/xen-orchestra-201927041953/packages/xo-server/dist/xapi/index.js:88:103)
    at _next (/etc/xo/xo-builds/xen-orchestra-201927041953/packages/xo-server/dist/xapi/index.js:90:194)
    at /etc/xo/xo-builds/xen-orchestra-201927041953/packages/xo-server/dist/xapi/index.js:90:364
    at Promise._execute (/etc/xo/xo-builds/xen-orchestra-201927041953/node_modules/bluebird/js/release/debuggability.js:313:9)
    at Promise._resolveFromExecutor (/etc/xo/xo-builds/xen-orchestra-201927041953/node_modules/bluebird/js/release/promise.js:483:18)
    at new Promise (/etc/xo/xo-builds/xen-orchestra-201927041953/node_modules/bluebird/js/release/promise.js:79:10)
    at /etc/xo/xo-builds/xen-orchestra-201927041953/packages/xo-server/dist/xapi/index.js:90:97
    at Xapi.createCloudInitConfigDrive (/etc/xo/xo-builds/xen-orchestra-201927041953/packages/xo-server/src/xapi/index.js:2384:4)
    at Xapi.<anonymous> (/etc/xo/xo-builds/xen-orchestra-201927041953/node_modules/golike-defer/src/index.js:60:48)
    at /etc/xo/xo-builds/xen-orchestra-201927041953/packages/xo-server/src/xapi/mixins/vm.js:248:19
    at Generator.next (<anonymous>)
    at asyncGeneratorStep (/etc/xo/xo-builds/xen-orchestra-201927041953/packages/xo-server/dist/xapi/mixins/vm.js:42:103)
    at _next (/etc/xo/xo-builds/xen-orchestra-201927041953/packages/xo-server/dist/xapi/mixins/vm.js:44:194)
    at tryCatcher (/etc/xo/xo-builds/xen-orchestra-201927041953/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/etc/xo/xo-builds/xen-orchestra-201927041953/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/etc/xo/xo-builds/xen-orchestra-201927041953/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/etc/xo/xo-builds/xen-orchestra-201927041953/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/etc/xo/xo-builds/xen-orchestra-201927041953/node_modules/bluebird/js/release/promise.js:694:18)
    at _drainQueueStep (/etc/xo/xo-builds/xen-orchestra-201927041953/node_modules/bluebird/js/release/async.js:138:12)
    at _drainQueue (/etc/xo/xo-builds/xen-orchestra-201927041953/node_modules/bluebird/js/release/async.js:131:9)
    at Async._drainQueues (/etc/xo/xo-builds/xen-orchestra-201927041953/node_modules/bluebird/js/release/async.js:147:5)
    at Immediate.Async.drainQueues (/etc/xo/xo-builds/xen-orchestra-201927041953/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:810:20)
    at tryOnImmediate (timers.js:768:5)
    at processImmediate [as _immediateCallback] (timers.js:745:5)"
}
```

After checking the UUIDs, everything seems to be right but not sure why XO is failing.

```
# Network UUID (Correct, belongs to host2)
"network": "8b2a3e6d-a401-3f07-3436-1434e192df25"

# SR UUID (Correct, belongs to host2)
"$SR": "388ccc18-9b21-22cc-dfa9-db4c8c3a4959",

# Template UUID (Correct, belongs to host2)
"template": "74ae424d-a1d3-4d96-9827-d1d60a4c7511"
```

**Comment by ddelnano** [comment]
@olivierlambert using the data resource PIF should work. Many of the acceptance tests use that (example [here](https://github.com/terra-farm/terraform-provider-xenorchestra/blob/master/xoa/resource_xenorchestra_vm_test.go#L143)).

@trigun539 to rule out terraform have you tried using the XO cli to create the vm you want and we can compare that invocation to what terraform is doing? I have never used this provider with more than one host and there have been multiple issues around this #10 and the issues you've filed.

**Comment by trigun539** [comment]
@ddelnano trying out xo-cli, could you point me to an example of creating a VM with xo-cli?

**Comment by trigun539** [comment]
Here is the xo-cli output:

```bash
xo-cli vm.create \
  CPUs=2 \
  VIFs='json:[{"network": "8b2a3e6d-a401-3f07-3436-1434e192df25"}]' \
  bootAfterCreate=true \
  cloudConfig= "#cloud-init\ntiemzone: America/New_York\nhostname: terraformtest\npackage_update: true\npackage_upgrade: true\nusers:\n  - name: test\n    gecos: Test User\n    groups: sudo\n    passwd: test\n    sudo: ['ALL=(ALL) NOPASSWD:ALL']\n\nnetwork:\n  version: 2\n  ethernets:\n    eno1:\n      dhcp4: no\n      addresses: [192.168.0.42/24]\n      gateway4: 192.168.0.1\n      nameservers:\n         addresses: [192.168.0.1]" \
  coreOs=false \
  cpuCap=null \
  cpuWeight=null \
  existingDisks='json:{"0": { "$SR": "388ccc18-9b21-22cc-dfa9-db4c8c3a4959", "name_label": "Terraform_disk_imavo", "size": 32212254720 } }' \
  memoryMax='1073733632' \
  name_description='testxoclidesc' \
  name_label='testxocli' \
  template=74ae424d-a1d3-4d96-9827-d1d60a4c7511
```

Error:

```
sh xo-cli-test.sh
✖ unknown error from the peer
JsonRpcError: unknown error from the peer
    at Peer._callee$ (/usr/local/lib/node_modules/xo-cli/node_modules/json-rpc-peer/dist/index.js:212:17)
    at tryCatch (/usr/local/lib/node_modules/xo-cli/node_modules/babel-runtime/node_modules/regenerator-runtime/runtime.js:62:40)
    at Generator.invoke [as _invoke] (/usr/local/lib/node_modules/xo-cli/node_modules/babel-runtime/node_modules/regenerator-runtime/runtime.js:296:22)
    at Generator.prototype.<computed> [as next] (/usr/local/lib/node_modules/xo-cli/node_modules/babel-runtime/node_modules/regenerator-runtime/runtime.js:114:21)
    at step (/usr/local/lib/node_modules/xo-cli/node_modules/babel-runtime/helpers/asyncToGenerator.js:17:30)
    at /usr/local/lib/node_modules/xo-cli/node_modules/babel-runtime/helpers/asyncToGenerator.js:35:14
    at new Promise (<anonymous>)
    at new F (/usr/local/lib/node_modules/xo-cli/node_modules/core-js/library/modules/_export.js:36:28)
    at Peer.<anonymous> (/usr/local/lib/node_modules/xo-cli/node_modules/babel-runtime/helpers/asyncToGenerator.js:14:12)
    at Peer.exec (/usr/local/lib/node_modules/xo-cli/node_modules/json-rpc-peer/dist/index.js:256:21)
    at Peer.write (/usr/local/lib/node_modules/xo-cli/node_modules/json-rpc-peer/dist/index.js:367:12)
    at Xo.<anonymous> (/usr/local/lib/node_modules/xo-cli/node_modules/jsonrpc-websocket-client/dist/index.js:92:12)
    at Xo.emit (events.js:200:13)
    at WebSocket.<anonymous> (/usr/local/lib/node_modules/xo-cli/node_modules/jsonrpc-websocket-client/dist/websocket-client.js:232:20)
    at WebSocket.onMessage (/usr/local/lib/node_modules/xo-cli/node_modules/ws/lib/EventTarget.js:99:16)
    at WebSocket.emit (events.js:200:13)

```

**Comment by ddelnano** [comment]
It's been a long time since this issue was created and I'm not sure there is a good lead for solving this issue. @trigun539 if you are still having problems, I would be happy to help over Discord (as mentioned in the README).
