### ISSUE TITLE
Crash when talking to an unresponsive XOA

### ISSUE THREAD

**Issue by brd** [terra-farm/terraform-provider-xenorchestra#81]
Using 0.7.2 of the provider and earlier, try pointing XOA_URL to any random IP:

```
terraform plan -lock=false
Refreshing Terraform state in-memory prior to plan...
The refreshed state will be used to calculate this plan, but will not be
persisted to local or remote state storage.

data.xenorchestra_sr.nas1-sr0: Refreshing state...
data.xenorchestra_network.site1-1201: Refreshing state...
data.xenorchestra_sr.nas1-sr0: Refreshing state...
data.xenorchestra_network.site1-1301: Refreshing state...
data.xenorchestra_template.centos: Refreshing state...

Error: rpc error: code = Unavailable desc = transport is closing



Error: context deadline exceeded

  on main.tf line 153, in data "xenorchestra_sr" "nas1-sr0":
 153: data "xenorchestra_sr" "nas1-sr0" {


panic: runtime error: invalid memory address or nil pointer dereference
2020-10-19T14:18:36.307Z [DEBUG] plugin.terraform-provider-xenorchestra_v0.7.2: [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xda7a9a]
2020-10-19T14:18:36.307Z [DEBUG] plugin.terraform-provider-xenorchestra_v0.7.2: 
2020-10-19T14:18:36.307Z [DEBUG] plugin.terraform-provider-xenorchestra_v0.7.2: goroutine 44 [running]:
2020-10-19T14:18:36.307Z [DEBUG] plugin.terraform-provider-xenorchestra_v0.7.2: github.com/ddelnano/terraform-provider-xenorchestra/client.(*Client).Call(0x0, 0x1176b00, 0xc0002a8120, 0x1000185, 0x10, 0xeb3ea0, 0xc0002b0300, 0xe34be0, 0xc0002ec260, 0x0, ...)
2020-10-19T14:18:36.307Z [DEBUG] plugin.terraform-provider-xenorchestra_v0.7.2: 	github.com/ddelnano/terraform-provider-xenorchestra/client/client.go:92 +0x3a
2020-10-19T14:18:36.307Z [DEBUG] plugin.terraform-provider-xenorchestra_v0.7.2: github.com/ddelnano/terraform-provider-xenorchestra/client.(*Client).GetAllObjectsOfType(0x0, 0x1160fa0, 0xc0002f44c0, 0xe34be0, 0xc0002ec260, 0xc000129900, 0xc0005cb718)
2020-10-19T14:18:36.307Z [DEBUG] plugin.terraform-provider-xenorchestra_v0.7.2: 	github.com/ddelnano/terraform-provider-xenorchestra/client/client.go:150 +0x205
2020-10-19T14:18:36.307Z [DEBUG] plugin.terraform-provider-xenorchestra_v0.7.2: github.com/ddelnano/terraform-provider-xenorchestra/client.(*Client).FindFromGetAllObjects(0x0, 0x1160fa0, 0xc0002f44c0, 0xc0002f44c0, 0xc000438c80, 0xe53d40, 0xe53d40)
2020-10-19T14:18:36.307Z [DEBUG] plugin.terraform-provider-xenorchestra_v0.7.2: 	github.com/ddelnano/terraform-provider-xenorchestra/client/client.go:157 +0x8e
2020-10-19T14:18:36.307Z [DEBUG] plugin.terraform-provider-xenorchestra_v0.7.2: github.com/ddelnano/terraform-provider-xenorchestra/client.(*Client).GetNetwork(0x0, 0x0, 0x0, 0xc0002f72c0, 0x13, 0x0, 0x0, 0x0, 0x0, 0x8000102, ...)
2020-10-19T14:18:36.307Z [DEBUG] plugin.terraform-provider-xenorchestra_v0.7.2: 	github.com/ddelnano/terraform-provider-xenorchestra/client/network.go:56 +0x94
2020-10-19T14:18:36.307Z [DEBUG] plugin.terraform-provider-xenorchestra_v0.7.2: github.com/ddelnano/terraform-provider-xenorchestra/xoa.dataSourceNetworkRead(0xc0003dc770, 0xf2d2a0, 0xc000417ec0, 0xc0003dc770, 0x0)
2020-10-19T14:18:36.307Z [DEBUG] plugin.terraform-provider-xenorchestra_v0.7.2: 	github.com/ddelnano/terraform-provider-xenorchestra/xoa/data_source_xenorchestra_network.go:36 +0x225
2020-10-19T14:18:36.307Z [DEBUG] plugin.terraform-provider-xenorchestra_v0.7.2: github.com/hashicorp/terraform-plugin-sdk/helper/schema.(*Resource).ReadDataApply(0xc0003833b0, 0xc000680640, 0xf2d2a0, 0xc000417ec0, 0xc0003858e8, 0x1, 0x0)
2020-10-19T14:18:36.307Z [DEBUG] plugin.terraform-provider-xenorchestra_v0.7.2: 	github.com/hashicorp/terraform-plugin-sdk@v1.15.0/helper/schema/resource.go:403 +0x88
2020-10-19T14:18:36.307Z [DEBUG] plugin.terraform-provider-xenorchestra_v0.7.2: github.com/hashicorp/terraform-plugin-sdk/helper/schema.(*Provider).ReadDataApply(0xc0000f0900, 0xc000103ad0, 0xc000680640, 0xc000680640, 0x0, 0x0)
2020-10-19T14:18:36.307Z [DEBUG] plugin.terraform-provider-xenorchestra_v0.7.2: 	github.com/hashicorp/terraform-plugin-sdk@v1.15.0/helper/schema/provider.go:451 +0x8f
2020-10-19T14:18:36.307Z [DEBUG] plugin.terraform-provider-xenorchestra_v0.7.2: github.com/hashicorp/terraform-plugin-sdk/internal/helper/plugin.(*GRPCProviderServer).ReadDataSource(0xc00000ec68, 0x1176b40, 0xc00011a9f0, 0xc0002f4f80, 0xc00000ec68, 0xc00011a9f0, 0xc00007fb78)
2020-10-19T14:18:36.307Z [DEBUG] plugin.terraform-provider-xenorchestra_v0.7.2: 	github.com/hashicorp/terraform-plugin-sdk@v1.15.0/internal/helper/plugin/grpc_provider.go:1036 +0x42d
2020-10-19T14:18:36.307Z [DEBUG] plugin.terraform-provider-xenorchestra_v0.7.2: github.com/hashicorp/terraform-plugin-sdk/internal/tfplugin5._Provider_ReadDataSource_Handler(0xfbc5e0, 0xc00000ec68, 0x1176b40, 0xc00011a9f0, 0xc0002e7b00, 0x0, 0x1176b40, 0xc00011a9f0, 0xc0002f0280, 0x4f)
2020-10-19T14:18:36.307Z [DEBUG] plugin.terraform-provider-xenorchestra_v0.7.2: 	github.com/hashicorp/terraform-plugin-sdk@v1.15.0/internal/tfplugin5/tfplugin5.pb.go:3341 +0x214
2020-10-19T14:18:36.308Z [DEBUG] plugin.terraform-provider-xenorchestra_v0.7.2: google.golang.org/grpc.(*Server).processUnaryRPC(0xc000001e00, 0x117fe80, 0xc0005e0480, 0xc0000e5800, 0xc000417200, 0x1712850, 0x0, 0x0, 0x0)
2020-10-19T14:18:36.308Z [DEBUG] plugin.terraform-provider-xenorchestra_v0.7.2: 	google.golang.org/grpc@v1.27.1/server.go:1024 +0x522
2020-10-19T14:18:36.308Z [DEBUG] plugin.terraform-provider-xenorchestra_v0.7.2: google.golang.org/grpc.(*Server).handleStream(0xc000001e00, 0x117fe80, 0xc0005e0480, 0xc0000e5800, 0x0)
2020-10-19T14:18:36.308Z [DEBUG] plugin.terraform-provider-xenorchestra_v0.7.2: 	google.golang.org/grpc@v1.27.1/server.go:1313 +0xd34
2020-10-19T14:18:36.308Z [DEBUG] plugin.terraform-provider-xenorchestra_v0.7.2: google.golang.org/grpc.(*Server).serveStreams.func1.1(0xc0002ee1c0, 0xc000001e00, 0x117fe80, 0xc0005e0480, 0xc0000e5800)
2020-10-19T14:18:36.308Z [DEBUG] plugin.terraform-provider-xenorchestra_v0.7.2: 	google.golang.org/grpc@v1.27.1/server.go:722 +0xa5
2020-10-19T14:18:36.308Z [DEBUG] plugin.terraform-provider-xenorchestra_v0.7.2: created by google.golang.org/grpc.(*Server).serveStreams.func1
2020-10-19T14:18:36.308Z [DEBUG] plugin.terraform-provider-xenorchestra_v0.7.2: 	google.golang.org/grpc@v1.27.1/server.go:720 +0xa5
2020/10/19 14:18:36 [ERROR] eval: *terraform.evalReadDataRefresh, err: rpc error: code = Unavailable desc = transport is closing
2020/10/19 14:18:36 [ERROR] eval: *terraform.EvalSequence, err: rpc error: code = Unavailable desc = transport is closing
2020/10/19 14:18:36 [TRACE] [walkRefresh] Exiting eval tree: data.xenorchestra_network.site1-1301
2020/10/19 14:18:36 [TRACE] vertex "data.xenorchestra_network.site1-1301": visit complete
2020/10/19 14:18:36 [TRACE] vertex "data.xenorchestra_network.site1-1301": dynamic subgraph encountered errors
2020/10/19 14:18:36 [TRACE] vertex "data.xenorchestra_network.site1-1301": visit complete
2020/10/19 14:18:36 [TRACE] vertex "data.xenorchestra_network.site1-1301 (expand)": dynamic subgraph encountered errors
2020/10/19 14:18:36 [TRACE] vertex "data.xenorchestra_network.site1-1301 (expand)": visit complete
2020/10/19 14:18:36 [TRACE] dag/walk: upstream of "provider[\"registry.terraform.io/terra-farm/xenorchestra\"] (close)" errored, so skipping
2020/10/19 14:18:36 [TRACE] dag/walk: upstream of "root" errored, so skipping
2020-10-19T14:18:36.311Z [WARN]  plugin.stdio: received EOF, stopping recv loop: err="rpc error: code = Unavailable desc = transport is closing"
2020-10-19T14:18:36.311Z [DEBUG] plugin: plugin process exited: path=.terraform/plugins/registry.terraform.io/terra-farm/xenorchestra/0.7.2/freebsd_amd64/terraform-provider-xenorchestra_v0.7.2 pid=69870 error="exit status 2"
2020-10-19T14:18:36.311Z [DEBUG] plugin: plugin exited



!!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!

Terraform crashed! This is always indicative of a bug within Terraform.
A crash log has been placed at "crash.log" relative to your current
working directory. It would be immensely helpful if you could please
report the crash with Terraform[1] so that we can fix this.

When reporting bugs, please include your terraform version. That
information is available on the first line of crash.log. You can also
get it by running 'terraform --version' on the command line.

SECURITY WARNING: the "crash.log" file that was created may contain 
sensitive information that must be redacted before it is safe to share 
on the issue tracker.

[1]: https://github.com/hashicorp/terraform/issues

!!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!
```

It probably should exit more gracefully

**Comment by ddelnano** [comment]
This is fixed in v0.7.3
